version: "3"

services:
  django:
    build: .
    image: django_server
    container_name: django_server
    ports:
      - "8000:8000"
    volumes:
      - ".:/opt/"
    working_dir: /opt/
    restart: always
    tty: true
    command: uvicorn --host 0.0.0.0 web.asgi:application
