version: "3"

services:
  web:
    build: .
    image: http_server:latest
    container_name: http_server
    ports:
      - "8080:8080"
    restart: always
    volumes:
      - ".:/opt/"
    working_dir: "/opt/"
    command: python 02-ssession_counter.py
