version: "3"

services:
  web:
    build: .
    image: web_server
    container_name: web_server
    ports:
      - "80:8000"
    restart: always
    volumes:
      - ".:/opt/"
    working_dir: "/opt/"
    command: python server.py

  db:
    image: mysql
    container_name: db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: pwd
    volumes:
      - "./db_data:/var/lib/mysql"
    ports:
      - 3306:3306

  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - 8080:8080
